// 
export const SET_USERNAME = 'SET_USERNAME';

//smile
export const SET_SMILE_IMG = 'SET_SMILE_IMG';
export const SET_MEMOIRS_IMG = 'SET_MEMOIRS_IMG';
export const SET_MOSTBEAUTIFUL_IMG = 'SET_MOSTBEAUTIFUL_IMG';